### ISSUE TITLE
What's with user -1?

### ISSUE THREAD

**Issue by rjmagley** [LoganMeitz/votefinder#3]
Is that the no execute/nobody voted choice? Why does it have to be there? If there's a good reason for this, it would be nice to have it set up automatically rather than needing to fiddle with the DB in the shell beforehand.

**Comment by davidcbc** [comment]
It's hardcoded as the no execute player here: https://github.com/LoganMeitz/votefinder/blob/20899d1efb2182cf052b4bac277f6c7b0b689e28/votefinder/main/VoteCounter.py#L100

**Comment by movexig** [comment]
Init fixture contains this player and an anonymous player (which is also required) now. In the future we might want to remove these requirements but this is where it stands now.
