### ISSUE TITLE
Vote image is unreadable on dark backgrounds

### ISSUE THREAD

**Issue by movexig** [LoganMeitz/votefinder#8]
Many users use SA in dark mode. The black-on-transparent votecount image is almost unreadable in dark mode.

I've tried a couple of variants, but the quickest fix would be to just not have the background image transparent, but a solid color instead. Another alternative is to attempt some kind of light outline around text (which is doable with Pillow just fine).

**Comment by rjmagley** [comment]
A solid color is probably best for now. Pretty sure I can fix this today.

**Comment by rjmagley** [comment]
it would be hilarious if we instead generated SVG images and used some trickery to just invert the text color

I don't think we should but, again, amusing

**Comment by rjmagley** [comment]
So I definitely didn't fix this a week ago, but I sure will start on it now.

This might also be a nice opportunity to take all this image-drawing code out of views.py to tidy it up a bit, get all the related code in one .py file - IIRC there are like three or four functions called to make the image, and they're all distributed throughout views.py. May as well organize them into one location to make it easier to work on this stuff later.

**Comment by rjmagley** [comment]
I think this is fixed with this PR, we'll want to test it to be sure

**Comment by rjmagley** [comment]
Fixed alongside everything else in `pillow-10-update`.
